---

# create the cert_user
- name: Create non-root user for certificate server access
  user:
    name: "{{ cert_server_user }}"
    shell: "/bin/bash"

# add ACL to give certificate server user read access to current certificates
- name: Give certificate server user access to letsencrypt directory
  acl:
    name: /etc/letsencrypt
    state: present
    permissions: rX
    entity: "{{ cert_server_user }}"
    etype:  user

- name: Give certificate server user access to certificate subfolders
  acl:
    name: "{{ item }}"
    state: present
    permissions: rX
    entity: "{{ cert_server_user }}"
    etype:  user
    recursive: yes
  with_items:
    - /etc/letsencrypt/live
    - /etc/letsencrypt/archive

- name: Give certificate server user access to new files in certificate subfolders
  acl:
    name: "{{ item }}"
    state: present
    permissions: rX
    entity: "{{ cert_server_user }}"
    etype:  user
    recursive: yes
    default: yes
  with_items:
    - /etc/letsencrypt/live
    - /etc/letsencrypt/archive
