---

www_uploads_dir: /var/thecombine/uploads
www_uploads_owner: www-data
www_uploads_group: www-data

www_app_dir: "/var/www/{{ ansible_fqdn }}/htdocs"
www_app_owner: www-data
www_app_group: www-data

combine_backend_dir: /home/combine/Backend

combine_env_vars:
  ASPNETCORE_ENVIRONMENT: Production
  DOTNET_PRINT_TELEMETRY_MESSAGE: false
