---
#################################################
# Group specific configuration items
#
# Group: nuc
#################################################

config_base_url: "https://thecombine.languagetechnology.org/v1"
config_captcha_required: "false"
config_captcha_sitekey: ""

#wifi access point variables
ap_ssid: "{{ ansible_hostname }}_ap"
ap_gateway: "10.10.10.1"
ap_domain: "{{ url_domain }}"
ap_hostname: "{{ url_hostname }}"
ap_passphrase: "Combine@5247"
# Make sure that the Access Point is not started until after the Firewall is
# up so that starting the firewall does not undo all the access point routings
ap_start_service_after:
  - "csf.service"

#apache web server config items
apache_listen_address: "{{ ap_gateway }}"

#set backend logging levels
app_loglevel: "Debug"
sys_loglevel: "Debug"
ms_loglevel: "Debug"
