---
#################################################
# Group specific configuration items
#
# Group: nuc
#################################################

config_base_url: "https://thecombine.languagetechnology.org/v1"
config_captcha_required: "false"
config_captcha_sitekey: ""

#wifi access point variables
ap_ssid: "{{ ansible_hostname }}_ap"
ap_gateway: "10.10.10.1"
ap_domain: "{{ url_domain }}"
ap_hostname: "{{ url_hostname }}"
ap_passphrase: "Combine@5247"
# Make sure that the Access Point is not started until after the Firewall is
# up so that starting the firewall does not undo all the access point routings
ap_start_service_after:
  - "csf.service"

#apache web server config items
apache_listen_address: "{{ ap_gateway }}"

#set backend logging levels
app_loglevel: "Debug"
sys_loglevel: "Debug"
ms_loglevel: "Debug"

#ConfigServer Firewall (csf) configuration items
csf_config_ports:
  tcp4_in:
    - 22
    - 80
    - 443
    - 873
  tcp4_out:
    - 22
    - 53
    - 80
    - 110
    - 443
    - 465
    - 587
    - 873
    - 5353
  udp4_in:
    - 53
    - 67
  udp4_out:
    - 53
    - 68
    - 5353

csf_config_allow: []
#  - { ip: 10.1.2.3, comment: 'some comment'}

csf_config_testing: 0
csf_config_auto_updates: 0
# Configure for all interfaces (except loopback)
csf_config_device: ""
csf_config_alert_ssh_email: 0

csf_config_process_limit: 60
csf_config_process_interval: 60
csf_config_process_skip_http: 0
csf_config_process_deleted: 0
csf_config_process_deleted_action: ""
csf_config_process_userproc: 10
csf_config_process_usermem: 250
csf_config_process_usertime: 1800
csf_config_process_userkill: 0
csf_config_process_userkill_alert: 1
csf_config_process_user_action: ""
csf_config_process_load: 30
csf_config_process_load_avg: 5
csf_config_process_load_level: 6
csf_config_process_load_skip: 3600
csf_config_process_apachestatus: "http://127.0.0.1/server-status"
csf_config_process_load_action: ""
csf_config_process_forkbomb: 0
csf_config_process_sshdhung: 0

csf_config_dyndns: 0
csf_config_dyndns_ignore: 0
csf_dyndns_allow: []
  # - protocol: "udp"
  #   direction: "out"
  #   port: "d=123"
  #   domain: "d=ntp.ubuntu.com"
  # - protocol: "tcp"
  #   direction: "out"
  #   port: "d=80"
  #   domain: "d=archive.ubuntu.com"
  # - protocol: "tcp"
  #   direction: "out"
  #   port: "d=443"
  #   domain: "d=archive.ubuntu.com"
  # - protocol: "tcp"
  #   direction: "out"
  #   port: "d=80"
  #   domain: "d=security.ubuntu.com"
  # - protocol: "tcp"
  #   direction: "out"
  #   port: "d=443"
  #   domain: "d=security.ubuntu.com"
  # - protocol: "tcp"
  #   direction: "out"
  #   port: "d=443"
  #   domain: "d=api.snapcraft.io"
  # - protocol: "tcp"
  #   direction: "out"
  #   port: "d=80"
  #   domain: "d=us-east-1.ec2.archive.ubuntu.com"
  # - protocol: "tcp"
  #   direction: "out"
  #   port: "d=443"
  #   domain: "d=us-east-1.ec2.archive.ubuntu.com"

csf_config_lfd_interval: 600
csf_config_lfd_blocks:
  - name: "SSHD"
    limit: 10
    time:  600
  - name: "FTPD"
    limit: 5
    time:  7200
  - name: "SMTPAUTH"
    limit: 5
    time:  7200
  - name: "POP3D"
    limit: 5
    time:  7200
  - name: "IMAPD"
    limit: 5
    time:  7200
  - name: "HTACCESS"
    limit: 5
    time:  1
  - name: "MODSEC"
    limit: 5
    time:  1
  - name: "BIND"
    limit: 0
    time:  1

csf_config_lfd_dist_ftp:
  limit:  5
  unique: 3
  time:   3600
  alert:  1

csf_config_port_scan:
  interval: 300
  limit:    10

csf_config_port_knocking:
  alert: 0

# The ST_ variables set system logging / graphing options. Currently we don't use these.
csf_config_system:
  enabled: 0

csf_config_logs:
  - name: "HTACCESS"
    file: "/var/log/apache2/error.log"
  - name: "MODSEC"
    file: "/var/log/apache2/error.log"
  - name: "SSHD"
    file: "/var/log/auth.log"
  - name: "SU"
    file: "/var/log/messages"
  - name: "FTPD"
    file: "/var/log/daemon.log"
  - name: "SMTPAUTH"
    file: "/var/log/mail.log"
  - name: "POP3D"
    file: "/var/log/mail.log"
  - name: "IMAPD"
    file: "/var/log/mail.log"
  - name: "IPTABLES"
    file: "/var/log/messages"
  - name: "SUHOSIN"
    file: "/var/log/messages"
  - name: "BIND"
    file: "/var/log/messages"
  - name: "SYSLOG"
    file: "/var/log/syslog"
  - name: "WEBMIN"
    file: "/var/log/auth.log"

csf_config_logs_custom:
  - name: "CUSTOM1"
    file: "/var/log/mail.log"
  - name: "CUSTOM2"
    file: "/var/log/customlog"
  - name: "CUSTOM3"
    file: "/var/log/customlog"
  - name: "CUSTOM4"
    file: "/var/log/customlog"
  - name: "CUSTOM5"
    file: "/var/log/customlog"
  - name: "CUSTOM6"
    file: "/var/log/customlog"
  - name: "CUSTOM7"
    file: "/var/log/customlog"
  - name: "CUSTOM8"
    file: "/var/log/customlog"
  - name: "CUSTOM9"
    file: "/var/log/customlog"

csf_config_pignore:
  lines:
    - "pexe:/usr/lib/postfix/.*"
    - "exe:/usr/sbin/atd"
    - "exe:/usr/sbin/sshd"
    - "exe:/bin/dbus-daemon"
    - "exe:/usr/bin/dbus-daemon"
    - "user:ubuntu"
