---

- name: Setup TheCombine Demo Server
  hosts: server
  gather_facts: yes
  become: yes


  vars_files:
    - "vars/config_common.yml"

  tasks:
    - name: Add ssh keys for NUCs setup to date
      import_role:
        name: add_ssh_keys
      tags: [ 'register_client' ]
