---

##############################################################
#
# This file lists the roles that need to be installed from
# Ansible Galaxy.  If you do not use the setup-target.sh
# script in the deploy directory to run the playbook, you
# can install these roles by running the following command
#
#   ansible-galaxy -r requirements.yml -p roles_galaxy
#
# (from the deploy directory).
#
##############################################################

- src: geerlingguy.certbot
- src: geerlingguy.pip
- src: geerlingguy.apache
