---

- name: Import public key for node.js repository
  apt_key:
    url:   https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Add repository for node.js
  apt_repository:
    repo: deb https://deb.nodesource.com/{{ nodejs_repo }} {{ ansible_distribution_release }} main
    state: present

- name: Add src repository for node.js
  apt_repository:
    repo: deb-src https://deb.nodesource.com/{{ nodejs_repo }} {{ ansible_distribution_release }} main
    state: present

- name: Install nodejs
  apt:
    name: "{{ nodejs_pkg }}"
    state: present
